/*
* generated by Xtext
*/
package org.hepaxcodex.eVHDL.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class VHDLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
