/*
 * generated by Xtext
 */
package org.hepaxcodex.eVHDL;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VHDLRuntimeModule extends org.hepaxcodex.eVHDL.AbstractVHDLRuntimeModule {

}
