/*
* generated by Xtext
*/
package org.hepaxcodex.eVHDL.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.hepaxcodex.eVHDL.services.VHDLGrammarAccess;

public class VHDLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private VHDLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.hepaxcodex.eVHDL.parser.antlr.internal.InternalVHDLParser createParser(XtextTokenStream stream) {
		return new org.hepaxcodex.eVHDL.parser.antlr.internal.InternalVHDLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "vHDLPagckage";
	}
	
	public VHDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(VHDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
