/*
* generated by Xtext
*/
package org.hepaxcodex.eVHDL.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VHDLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/hepaxcodex/eVHDL/parser/antlr/internal/InternalVHDL.tokens");
	}
}
