/*
* generated by Xtext
*/
package org.hepaxcodex.eVHDL.ui.contentassist;

import org.hepaxcodex.eVHDL.ui.contentassist.AbstractVHDLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class VHDLProposalProvider extends AbstractVHDLProposalProvider {

}
