/*
 * generated by Xtext
 */
package org.hepaxcodex.eVHDL.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VHDLUiModule extends org.hepaxcodex.eVHDL.ui.AbstractVHDLUiModule {
	public VHDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
